// <auto-generated />
using ConfiguratorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConfiguratorAPI.Data.Migrations
{
    [DbContext(typeof(ConfiguratorDbContext))]
    [Migration("20250527171930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfiguratorAPI.Models.Brand", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Code = "alfaromeo",
                            ImgUrl = "/brands/alfaromeo.webp",
                            IsActive = true,
                            Name = "Alfa Romeo"
                        },
                        new
                        {
                            Code = "audi",
                            ImgUrl = "/brands/audi.webp",
                            IsActive = true,
                            Name = "Audi"
                        },
                        new
                        {
                            Code = "bmw",
                            ImgUrl = "/brands/bmw.webp",
                            IsActive = true,
                            Name = "BMW"
                        },
                        new
                        {
                            Code = "byd",
                            ImgUrl = "/brands/byd.webp",
                            IsActive = true,
                            Name = "BYD"
                        },
                        new
                        {
                            Code = "chery",
                            ImgUrl = "/brands/chery.webp",
                            IsActive = true,
                            Name = "Chery"
                        },
                        new
                        {
                            Code = "chevrolet",
                            ImgUrl = "/brands/chevrolet.webp",
                            IsActive = true,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Code = "citroen",
                            ImgUrl = "/brands/citroen.webp",
                            IsActive = true,
                            Name = "Citroen"
                        },
                        new
                        {
                            Code = "cupra",
                            ImgUrl = "/brands/cupra.webp",
                            IsActive = true,
                            Name = "Cupra"
                        },
                        new
                        {
                            Code = "dacia",
                            ImgUrl = "/brands/dacia.webp",
                            IsActive = true,
                            Name = "Dacia"
                        },
                        new
                        {
                            Code = "fiat",
                            ImgUrl = "/brands/fiat.webp",
                            IsActive = true,
                            Name = "FIAT"
                        },
                        new
                        {
                            Code = "ford",
                            ImgUrl = "/brands/ford.webp",
                            IsActive = true,
                            Name = "Ford"
                        },
                        new
                        {
                            Code = "haval",
                            ImgUrl = "/brands/haval.webp",
                            IsActive = true,
                            Name = "Haval"
                        },
                        new
                        {
                            Code = "honda",
                            ImgUrl = "/brands/honda.webp",
                            IsActive = true,
                            Name = "Honda"
                        },
                        new
                        {
                            Code = "hyundai",
                            ImgUrl = "/brands/hyundai.webp",
                            IsActive = true,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Code = "jaguar",
                            ImgUrl = "/brands/jaguar.webp",
                            IsActive = true,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Code = "jeep",
                            ImgUrl = "/brands/jeep.webp",
                            IsActive = true,
                            Name = "Jeep"
                        },
                        new
                        {
                            Code = "kia",
                            ImgUrl = "/brands/kia.webp",
                            IsActive = true,
                            Name = "Kia"
                        },
                        new
                        {
                            Code = "landrover",
                            ImgUrl = "/brands/landrover.webp",
                            IsActive = true,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Code = "mahindra",
                            ImgUrl = "/brands/mahindra.webp",
                            IsActive = true,
                            Name = "Mahindra"
                        },
                        new
                        {
                            Code = "mercedes",
                            ImgUrl = "/brands/mercedes.webp",
                            IsActive = true,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Code = "mg",
                            ImgUrl = "/brands/mg.webp",
                            IsActive = true,
                            Name = "MG"
                        },
                        new
                        {
                            Code = "mini",
                            ImgUrl = "/brands/mini.webp",
                            IsActive = true,
                            Name = "Mini"
                        },
                        new
                        {
                            Code = "mitsubishi",
                            ImgUrl = "/brands/mitsubishi.webp",
                            IsActive = true,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Code = "nissan",
                            ImgUrl = "/brands/nissan.webp",
                            IsActive = true,
                            Name = "Nissan"
                        },
                        new
                        {
                            Code = "opel",
                            ImgUrl = "/brands/opel.webp",
                            IsActive = true,
                            Name = "Opel"
                        },
                        new
                        {
                            Code = "peugeot",
                            ImgUrl = "/brands/peugeot.webp",
                            IsActive = true,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Code = "porsche",
                            ImgUrl = "/brands/porsche.webp",
                            IsActive = true,
                            Name = "Porsche"
                        },
                        new
                        {
                            Code = "renault",
                            ImgUrl = "/brands/renault.webp",
                            IsActive = true,
                            Name = "Renault"
                        },
                        new
                        {
                            Code = "seat",
                            ImgUrl = "/brands/seat.webp",
                            IsActive = true,
                            Name = "SEAT"
                        },
                        new
                        {
                            Code = "skoda",
                            ImgUrl = "/brands/skoda.webp",
                            IsActive = true,
                            Name = "Skoda"
                        },
                        new
                        {
                            Code = "kgm",
                            ImgUrl = "/brands/kgm.webp",
                            IsActive = true,
                            Name = "KGM"
                        },
                        new
                        {
                            Code = "suzuki",
                            ImgUrl = "/brands/suzuki.webp",
                            IsActive = true,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Code = "toyota",
                            ImgUrl = "/brands/toyota.webp",
                            IsActive = true,
                            Name = "Toyota"
                        },
                        new
                        {
                            Code = "volkswagen",
                            ImgUrl = "/brands/volkswagen.webp",
                            IsActive = true,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Code = "volvo",
                            ImgUrl = "/brands/volvo.webp",
                            IsActive = true,
                            Name = "Volvo"
                        },
                        new
                        {
                            Code = "wallys",
                            ImgUrl = "/brands/wallys.webp",
                            IsActive = true,
                            Name = "Wallys"
                        });
                });

            modelBuilder.Entity("ConfiguratorAPI.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdministrativeFee")
                        .HasColumnType("numeric");

                    b.Property<string>("AdvancePaymentOptionsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AnnualKmStep")
                        .HasColumnType("integer");

                    b.Property<decimal>("DefaultResidualValuePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("numeric");

                    b.Property<int>("DurationStepMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableDynamicResidualValueCalculation")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableTieredPricing")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAnnualKm")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDurationMonths")
                        .HasColumnType("integer");

                    b.Property<int>("MinAnnualKm")
                        .HasColumnType("integer");

                    b.Property<int>("MinDurationMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("PurchaseOptionPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RegistrationFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StandardInterestRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StandardMarginRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Configuration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdministrativeFee = 150m,
                            AdvancePaymentOptionsCsv = "0,10,20,30",
                            AnnualKmStep = 5000,
                            DefaultResidualValuePercent = 0.30m,
                            DeliveryFee = 300m,
                            DurationStepMonths = 1,
                            EnableDynamicResidualValueCalculation = true,
                            EnableTieredPricing = true,
                            MaxAnnualKm = 30000,
                            MaxDurationMonths = 60,
                            MinAnnualKm = 10000,
                            MinDurationMonths = 12,
                            PurchaseOptionPercent = 40m,
                            RegistrationFee = 100m,
                            StandardInterestRate = 0.035m,
                            StandardMarginRate = 0.10m,
                            VatRate = 0.19m
                        });
                });

            modelBuilder.Entity("ConfiguratorAPI.Models.Model", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Code = "alfaromeo_giulia",
                            BrandId = "alfaromeo",
                            ImgUrl = "/models/alfaromeo/giulia.webp",
                            IsActive = true,
                            Name = "Giulia"
                        },
                        new
                        {
                            Code = "alfaromeo_stelvio",
                            BrandId = "alfaromeo",
                            ImgUrl = "/models/alfaromeo/stelvio.webp",
                            IsActive = true,
                            Name = "Stelvio"
                        },
                        new
                        {
                            Code = "audi_a3berline",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/a3berline.webp",
                            IsActive = true,
                            Name = "A3 Berline"
                        },
                        new
                        {
                            Code = "audi_q2",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/q2.webp",
                            IsActive = true,
                            Name = "Q2"
                        },
                        new
                        {
                            Code = "audi_q3",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/q3.webp",
                            IsActive = true,
                            Name = "Q3"
                        },
                        new
                        {
                            Code = "audi_q3sportback",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/q3sportback.webp",
                            IsActive = true,
                            Name = "Q3 Sportback"
                        },
                        new
                        {
                            Code = "audi_q8etron",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/q8etron.webp",
                            IsActive = true,
                            Name = "Q8 e-tron"
                        },
                        new
                        {
                            Code = "audi_q8sportbacketron",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/q8sportbacketron.webp",
                            IsActive = true,
                            Name = "Q8 Sportback e-tron"
                        },
                        new
                        {
                            Code = "audi_etrongt",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/etrongt.webp",
                            IsActive = true,
                            Name = "e-tron GT"
                        },
                        new
                        {
                            Code = "audi_q7",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/q7.webp",
                            IsActive = true,
                            Name = "Q7"
                        },
                        new
                        {
                            Code = "audi_q8",
                            BrandId = "audi",
                            ImgUrl = "/models/audi/q8.webp",
                            IsActive = true,
                            Name = "Q8"
                        },
                        new
                        {
                            Code = "bmw_1",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/1.webp",
                            IsActive = true,
                            Name = "1 Series"
                        },
                        new
                        {
                            Code = "bmw_2grancoupe",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/2grancoupe.webp",
                            IsActive = true,
                            Name = "2 Gran Coupé"
                        },
                        new
                        {
                            Code = "bmw_3",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/3.webp",
                            IsActive = true,
                            Name = "3 Series"
                        },
                        new
                        {
                            Code = "bmw_4grancoupe",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/4grancoupe.webp",
                            IsActive = true,
                            Name = "4 Gran Coupé"
                        },
                        new
                        {
                            Code = "bmw_5",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/5.webp",
                            IsActive = true,
                            Name = "5 Series"
                        },
                        new
                        {
                            Code = "bmw_i4",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/i4.webp",
                            IsActive = true,
                            Name = "i4"
                        },
                        new
                        {
                            Code = "bmw_i5",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/i5.webp",
                            IsActive = true,
                            Name = "i5"
                        },
                        new
                        {
                            Code = "bmw_ix",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/ix.webp",
                            IsActive = true,
                            Name = "iX"
                        },
                        new
                        {
                            Code = "bmw_ix1",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/ix1.webp",
                            IsActive = true,
                            Name = "iX1"
                        },
                        new
                        {
                            Code = "bmw_ix2",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/ix2.webp",
                            IsActive = true,
                            Name = "iX2"
                        },
                        new
                        {
                            Code = "bmw_ix3",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/ix3.webp",
                            IsActive = true,
                            Name = "iX3"
                        },
                        new
                        {
                            Code = "bmw_x1",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/x1.webp",
                            IsActive = true,
                            Name = "X1"
                        },
                        new
                        {
                            Code = "bmw_x1hybride",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/x1hybride.webp",
                            IsActive = true,
                            Name = "X1 Hybride"
                        },
                        new
                        {
                            Code = "bmw_x2",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/x2.webp",
                            IsActive = true,
                            Name = "X2"
                        },
                        new
                        {
                            Code = "bmw_x3hybride",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/x3hybride.webp",
                            IsActive = true,
                            Name = "X3 Hybride"
                        },
                        new
                        {
                            Code = "bmw_x4",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/x4.webp",
                            IsActive = true,
                            Name = "X4"
                        },
                        new
                        {
                            Code = "bmw_x5hybride",
                            BrandId = "bmw",
                            ImgUrl = "/models/bmw/x5hybride.webp",
                            IsActive = true,
                            Name = "X5 Hybride"
                        },
                        new
                        {
                            Code = "byd_atto3",
                            BrandId = "byd",
                            ImgUrl = "/models/byd/atto3.webp",
                            IsActive = true,
                            Name = "Atto 3"
                        },
                        new
                        {
                            Code = "byd_dolphin",
                            BrandId = "byd",
                            ImgUrl = "/models/byd/dolphin.webp",
                            IsActive = true,
                            Name = "Dolphin"
                        },
                        new
                        {
                            Code = "byd_king",
                            BrandId = "byd",
                            ImgUrl = "/models/byd/king.webp",
                            IsActive = true,
                            Name = "King"
                        },
                        new
                        {
                            Code = "byd_songplus",
                            BrandId = "byd",
                            ImgUrl = "/models/byd/songplus.webp",
                            IsActive = true,
                            Name = "Song Plus"
                        },
                        new
                        {
                            Code = "byd_tangev",
                            BrandId = "byd",
                            ImgUrl = "/models/byd/tangev.webp",
                            IsActive = true,
                            Name = "Tang EV"
                        },
                        new
                        {
                            Code = "chery_arrizo5",
                            BrandId = "chery",
                            ImgUrl = "/models/chery/arrizo5.webp",
                            IsActive = true,
                            Name = "Arrizo 5"
                        },
                        new
                        {
                            Code = "chery_tiggo3x",
                            BrandId = "chery",
                            ImgUrl = "/models/chery/tiggo3x.webp",
                            IsActive = true,
                            Name = "Tiggo 3X"
                        },
                        new
                        {
                            Code = "chery_tiggo4pro",
                            BrandId = "chery",
                            ImgUrl = "/models/chery/tiggo4pro.webp",
                            IsActive = true,
                            Name = "Tiggo 4 Pro"
                        },
                        new
                        {
                            Code = "chery_tiggo7pro",
                            BrandId = "chery",
                            ImgUrl = "/models/chery/tiggo7pro.webp",
                            IsActive = true,
                            Name = "Tiggo 7 Pro"
                        },
                        new
                        {
                            Code = "chery_tiggo8pro",
                            BrandId = "chery",
                            ImgUrl = "/models/chery/tiggo8pro.webp",
                            IsActive = true,
                            Name = "Tiggo 8 Pro"
                        },
                        new
                        {
                            Code = "chevrolet_captiva",
                            BrandId = "chevrolet",
                            ImgUrl = "/models/chevrolet/captiva.webp",
                            IsActive = true,
                            Name = "Captiva"
                        },
                        new
                        {
                            Code = "chevrolet_equinox",
                            BrandId = "chevrolet",
                            ImgUrl = "/models/chevrolet/equinox.webp",
                            IsActive = true,
                            Name = "Equinox"
                        },
                        new
                        {
                            Code = "chevrolet_groove",
                            BrandId = "chevrolet",
                            ImgUrl = "/models/chevrolet/groove.webp",
                            IsActive = true,
                            Name = "Groove"
                        },
                        new
                        {
                            Code = "citroen_berlingo",
                            BrandId = "citroen",
                            ImgUrl = "/models/citroen/berlingo.webp",
                            IsActive = true,
                            Name = "Berlingo"
                        },
                        new
                        {
                            Code = "citroen_berlingovan",
                            BrandId = "citroen",
                            ImgUrl = "/models/citroen/berlingovan.webp",
                            IsActive = true,
                            Name = "Berlingo Van"
                        },
                        new
                        {
                            Code = "citroen_c4x",
                            BrandId = "citroen",
                            ImgUrl = "/models/citroen/c4x.webp",
                            IsActive = true,
                            Name = "C4X"
                        },
                        new
                        {
                            Code = "citroen_jumper",
                            BrandId = "citroen",
                            ImgUrl = "/models/citroen/jumper.webp",
                            IsActive = true,
                            Name = "Jumper"
                        },
                        new
                        {
                            Code = "citroen_jumpyfourgon",
                            BrandId = "citroen",
                            ImgUrl = "/models/citroen/jumpyfourgon.webp",
                            IsActive = true,
                            Name = "Jumpy Fourgon"
                        },
                        new
                        {
                            Code = "cupra_formentor",
                            BrandId = "cupra",
                            ImgUrl = "/models/cupra/formentor.webp",
                            IsActive = true,
                            Name = "Formentor"
                        },
                        new
                        {
                            Code = "cupra_leon",
                            BrandId = "cupra",
                            ImgUrl = "/models/cupra/leon.webp",
                            IsActive = true,
                            Name = "Leon"
                        },
                        new
                        {
                            Code = "dacia_duster",
                            BrandId = "dacia",
                            ImgUrl = "/models/dacia/duster.webp",
                            IsActive = true,
                            Name = "Duster"
                        },
                        new
                        {
                            Code = "dacia_logan",
                            BrandId = "dacia",
                            ImgUrl = "/models/dacia/logan.webp",
                            IsActive = true,
                            Name = "Logan"
                        },
                        new
                        {
                            Code = "dacia_sandero",
                            BrandId = "dacia",
                            ImgUrl = "/models/dacia/sandero.webp",
                            IsActive = true,
                            Name = "Sandero"
                        },
                        new
                        {
                            Code = "dacia_sanderostepway",
                            BrandId = "dacia",
                            ImgUrl = "/models/dacia/sanderostepway.webp",
                            IsActive = true,
                            Name = "Sandero Stepway"
                        },
                        new
                        {
                            Code = "fiat_500",
                            BrandId = "fiat",
                            ImgUrl = "/models/fiat/500.webp",
                            IsActive = true,
                            Name = "500"
                        },
                        new
                        {
                            Code = "fiat_doblo",
                            BrandId = "fiat",
                            ImgUrl = "/models/fiat/doblo.webp",
                            IsActive = true,
                            Name = "Doblo"
                        },
                        new
                        {
                            Code = "fiat_doblocombi",
                            BrandId = "fiat",
                            ImgUrl = "/models/fiat/doblocombi.webp",
                            IsActive = true,
                            Name = "Doblo Combi"
                        },
                        new
                        {
                            Code = "fiat_ducato",
                            BrandId = "fiat",
                            ImgUrl = "/models/fiat/ducato.webp",
                            IsActive = true,
                            Name = "Ducato"
                        },
                        new
                        {
                            Code = "fiat_fiorinocombi",
                            BrandId = "fiat",
                            ImgUrl = "/models/fiat/fiorinocombi.webp",
                            IsActive = true,
                            Name = "Fiorino Combi"
                        },
                        new
                        {
                            Code = "fiat_tipoberline",
                            BrandId = "fiat",
                            ImgUrl = "/models/fiat/tipoberline.webp",
                            IsActive = true,
                            Name = "Tipo Berline"
                        },
                        new
                        {
                            Code = "ford_everest",
                            BrandId = "ford",
                            ImgUrl = "/models/ford/everest.webp",
                            IsActive = true,
                            Name = "Everest"
                        },
                        new
                        {
                            Code = "ford_ranger",
                            BrandId = "ford",
                            ImgUrl = "/models/ford/ranger.webp",
                            IsActive = true,
                            Name = "Ranger"
                        },
                        new
                        {
                            Code = "ford_rangerraptor",
                            BrandId = "ford",
                            ImgUrl = "/models/ford/rangerraptor.webp",
                            IsActive = true,
                            Name = "Ranger Raptor"
                        },
                        new
                        {
                            Code = "ford_transitvan",
                            BrandId = "ford",
                            ImgUrl = "/models/ford/transitvan.webp",
                            IsActive = true,
                            Name = "Transit Van"
                        },
                        new
                        {
                            Code = "haval_h6hybride",
                            BrandId = "haval",
                            ImgUrl = "/models/haval/h6hybride.webp",
                            IsActive = true,
                            Name = "H6 Hybride"
                        },
                        new
                        {
                            Code = "haval_jolion",
                            BrandId = "haval",
                            ImgUrl = "/models/haval/jolion.webp",
                            IsActive = true,
                            Name = "Jolion"
                        },
                        new
                        {
                            Code = "honda_accord",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/accord.webp",
                            IsActive = true,
                            Name = "Accord"
                        },
                        new
                        {
                            Code = "honda_city",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/city.webp",
                            IsActive = true,
                            Name = "City"
                        },
                        new
                        {
                            Code = "honda_civic",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/civic.webp",
                            IsActive = true,
                            Name = "Civic"
                        },
                        new
                        {
                            Code = "honda_civichybride",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/civichybride.webp",
                            IsActive = true,
                            Name = "Civic Hybride"
                        },
                        new
                        {
                            Code = "honda_civictyper",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/civictyper.webp",
                            IsActive = true,
                            Name = "Civic Type R"
                        },
                        new
                        {
                            Code = "honda_crv",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/crv.webp",
                            IsActive = true,
                            Name = "CR-V"
                        },
                        new
                        {
                            Code = "honda_crvhybride",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/crvhybride.webp",
                            IsActive = true,
                            Name = "CR-V Hybride"
                        },
                        new
                        {
                            Code = "honda_hrv",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/hrv.webp",
                            IsActive = true,
                            Name = "HR-V"
                        },
                        new
                        {
                            Code = "honda_jazz",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/jazz.webp",
                            IsActive = true,
                            Name = "Jazz"
                        },
                        new
                        {
                            Code = "honda_zrv",
                            BrandId = "honda",
                            ImgUrl = "/models/honda/zrv.webp",
                            IsActive = true,
                            Name = "ZR-V"
                        },
                        new
                        {
                            Code = "hyundai_azerahybride",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/azerahybride.webp",
                            IsActive = true,
                            Name = "Azera Hybride"
                        },
                        new
                        {
                            Code = "hyundai_creta",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/creta.webp",
                            IsActive = true,
                            Name = "Creta"
                        },
                        new
                        {
                            Code = "hyundai_i10",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/i10.webp",
                            IsActive = true,
                            Name = "i10"
                        },
                        new
                        {
                            Code = "hyundai_i10sedan",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/i10sedan.webp",
                            IsActive = true,
                            Name = "i10 Sedan"
                        },
                        new
                        {
                            Code = "hyundai_i20",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/i20.webp",
                            IsActive = true,
                            Name = "i20"
                        },
                        new
                        {
                            Code = "hyundai_ioniq5",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/ioniq5.webp",
                            IsActive = true,
                            Name = "IONIQ 5"
                        },
                        new
                        {
                            Code = "hyundai_kona",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/kona.webp",
                            IsActive = true,
                            Name = "Kona"
                        },
                        new
                        {
                            Code = "hyundai_konaelectric",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/konaelectric.webp",
                            IsActive = true,
                            Name = "Kona Electric"
                        },
                        new
                        {
                            Code = "hyundai_palisadecalligraphy",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/palisadecalligraphy.webp",
                            IsActive = true,
                            Name = "Palisade Calligraphy"
                        },
                        new
                        {
                            Code = "hyundai_staria",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/staria.webp",
                            IsActive = true,
                            Name = "Staria"
                        },
                        new
                        {
                            Code = "hyundai_tucson",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/tucson.webp",
                            IsActive = true,
                            Name = "Tucson"
                        },
                        new
                        {
                            Code = "hyundai_tucsonhybride",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/tucsonhybride.webp",
                            IsActive = true,
                            Name = "Tucson Hybride"
                        },
                        new
                        {
                            Code = "hyundai_venue",
                            BrandId = "hyundai",
                            ImgUrl = "/models/hyundai/venue.webp",
                            IsActive = true,
                            Name = "Venue"
                        },
                        new
                        {
                            Code = "jaguar_epace",
                            BrandId = "jaguar",
                            ImgUrl = "/models/jaguar/epace.webp",
                            IsActive = true,
                            Name = "E-Pace"
                        },
                        new
                        {
                            Code = "jaguar_fpace",
                            BrandId = "jaguar",
                            ImgUrl = "/models/jaguar/fpace.webp",
                            IsActive = true,
                            Name = "F-Pace"
                        },
                        new
                        {
                            Code = "jeep_renegade",
                            BrandId = "jeep",
                            ImgUrl = "/models/jeep/renegade.webp",
                            IsActive = true,
                            Name = "Renegade"
                        },
                        new
                        {
                            Code = "jeep_wrangler",
                            BrandId = "jeep",
                            ImgUrl = "/models/jeep/wrangler.webp",
                            IsActive = true,
                            Name = "Wrangler"
                        },
                        new
                        {
                            Code = "jeep_wranglerunlimited",
                            BrandId = "jeep",
                            ImgUrl = "/models/jeep/wranglerunlimited.webp",
                            IsActive = true,
                            Name = "Wrangler Unlimited"
                        },
                        new
                        {
                            Code = "kia_ev6",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/ev6.webp",
                            IsActive = true,
                            Name = "EV6"
                        },
                        new
                        {
                            Code = "kia_ev6gt",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/ev6gt.webp",
                            IsActive = true,
                            Name = "EV6 GT"
                        },
                        new
                        {
                            Code = "kia_nirohybride",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/nirohybride.webp",
                            IsActive = true,
                            Name = "Niro Hybride"
                        },
                        new
                        {
                            Code = "kia_picanto",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/picanto.webp",
                            IsActive = true,
                            Name = "Picanto"
                        },
                        new
                        {
                            Code = "kia_seltos",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/seltos.webp",
                            IsActive = true,
                            Name = "Seltos"
                        },
                        new
                        {
                            Code = "kia_sonet",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/sonet.webp",
                            IsActive = true,
                            Name = "Sonet"
                        },
                        new
                        {
                            Code = "kia_sportage",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/sportage.webp",
                            IsActive = true,
                            Name = "Sportage"
                        },
                        new
                        {
                            Code = "kia_sportagehypride",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/sportagehypride.webp",
                            IsActive = true,
                            Name = "Sportage Hybride"
                        },
                        new
                        {
                            Code = "kia_stonic",
                            BrandId = "kia",
                            ImgUrl = "/models/kia/stonic.webp",
                            IsActive = true,
                            Name = "Stonic"
                        },
                        new
                        {
                            Code = "landrover_defender110",
                            BrandId = "landrover",
                            ImgUrl = "/models/landrover/defender110.webp",
                            IsActive = true,
                            Name = "Defender 110"
                        },
                        new
                        {
                            Code = "landrover_evoque",
                            BrandId = "landrover",
                            ImgUrl = "/models/landrover/evoque.webp",
                            IsActive = true,
                            Name = "Evoque"
                        },
                        new
                        {
                            Code = "landrover_rangerover",
                            BrandId = "landrover",
                            ImgUrl = "/models/landrover/rangerover.webp",
                            IsActive = true,
                            Name = "Range Rover"
                        },
                        new
                        {
                            Code = "landrover_rangeroversport",
                            BrandId = "landrover",
                            ImgUrl = "/models/landrover/rangeroversport.webp",
                            IsActive = true,
                            Name = "Range Rover Sport"
                        },
                        new
                        {
                            Code = "landrover_velar",
                            BrandId = "landrover",
                            ImgUrl = "/models/landrover/velar.webp",
                            IsActive = true,
                            Name = "Velar"
                        },
                        new
                        {
                            Code = "mahindra_kuv100",
                            BrandId = "mahindra",
                            ImgUrl = "/models/mahindra/kuv100.webp",
                            IsActive = true,
                            Name = "KUV100"
                        },
                        new
                        {
                            Code = "mahindra_xuv300",
                            BrandId = "mahindra",
                            ImgUrl = "/models/mahindra/xuv300.webp",
                            IsActive = true,
                            Name = "XUV300"
                        },
                        new
                        {
                            Code = "mercedes_a",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/a.webp",
                            IsActive = true,
                            Name = "A-Class"
                        },
                        new
                        {
                            Code = "mercedes_aberline",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/aberline.webp",
                            IsActive = true,
                            Name = "A-Class Berline"
                        },
                        new
                        {
                            Code = "mercedes_c",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/c.webp",
                            IsActive = true,
                            Name = "C-Class"
                        },
                        new
                        {
                            Code = "mercedes_chybride",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/chybride.webp",
                            IsActive = true,
                            Name = "C-Class Hybride"
                        },
                        new
                        {
                            Code = "mercedes_cla",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/cla.webp",
                            IsActive = true,
                            Name = "CLA"
                        },
                        new
                        {
                            Code = "mercedes_clecoupe",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/clecoupe.webp",
                            IsActive = true,
                            Name = "CLE Coupé"
                        },
                        new
                        {
                            Code = "mercedes_e",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/e.webp",
                            IsActive = true,
                            Name = "E-Class"
                        },
                        new
                        {
                            Code = "mercedes_ehybride",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/ehybride.webp",
                            IsActive = true,
                            Name = "E-Class Hybride"
                        },
                        new
                        {
                            Code = "mercedes_eqeberline",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/eqeberline.webp",
                            IsActive = true,
                            Name = "EQE Berline"
                        },
                        new
                        {
                            Code = "mercedes_eqesuv",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/eqesuv.webp",
                            IsActive = true,
                            Name = "EQE SUV"
                        },
                        new
                        {
                            Code = "mercedes_eqsberline",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/eqsberline.webp",
                            IsActive = true,
                            Name = "EQS Berline"
                        },
                        new
                        {
                            Code = "mercedes_eqssuv",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/eqssuv.webp",
                            IsActive = true,
                            Name = "EQS SUV"
                        },
                        new
                        {
                            Code = "mercedes_gla",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/gla.webp",
                            IsActive = true,
                            Name = "GLA"
                        },
                        new
                        {
                            Code = "mercedes_glb",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/glb.webp",
                            IsActive = true,
                            Name = "GLB"
                        },
                        new
                        {
                            Code = "mercedes_glc",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/glc.webp",
                            IsActive = true,
                            Name = "GLC"
                        },
                        new
                        {
                            Code = "mercedes_glccoupe",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/glccoupe.webp",
                            IsActive = true,
                            Name = "GLC Coupé"
                        },
                        new
                        {
                            Code = "mercedes_glccoupehybride",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/glccoupehybride.webp",
                            IsActive = true,
                            Name = "GLC Coupé Hybride"
                        },
                        new
                        {
                            Code = "mercedes_glchybride",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/glchybride.webp",
                            IsActive = true,
                            Name = "GLC Hybride"
                        },
                        new
                        {
                            Code = "mercedes_gle",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/gle.webp",
                            IsActive = true,
                            Name = "GLE"
                        },
                        new
                        {
                            Code = "mercedes_glecoupe",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/glecoupe.webp",
                            IsActive = true,
                            Name = "GLE Coupé"
                        },
                        new
                        {
                            Code = "mercedes_s",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/s.webp",
                            IsActive = true,
                            Name = "S-Class"
                        },
                        new
                        {
                            Code = "mercedes_v",
                            BrandId = "mercedes",
                            ImgUrl = "/models/mercedes/v.webp",
                            IsActive = true,
                            Name = "V-Class"
                        },
                        new
                        {
                            Code = "mg_3",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/3.webp",
                            IsActive = true,
                            Name = "MG3"
                        },
                        new
                        {
                            Code = "mg_3hybride",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/3hybride.webp",
                            IsActive = true,
                            Name = "MG3 Hybride"
                        },
                        new
                        {
                            Code = "mg_4",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/4.webp",
                            IsActive = true,
                            Name = "MG4"
                        },
                        new
                        {
                            Code = "mg_5",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/5.webp",
                            IsActive = true,
                            Name = "MG5"
                        },
                        new
                        {
                            Code = "mg_7",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/7.webp",
                            IsActive = true,
                            Name = "MG7"
                        },
                        new
                        {
                            Code = "mg_ehs",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/ehs.webp",
                            IsActive = true,
                            Name = "eHS"
                        },
                        new
                        {
                            Code = "mg_ezs",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/ezs.webp",
                            IsActive = true,
                            Name = "eZS"
                        },
                        new
                        {
                            Code = "mg_gt",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/gt.webp",
                            IsActive = true,
                            Name = "GT"
                        },
                        new
                        {
                            Code = "mg_marvelr",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/marvelr.webp",
                            IsActive = true,
                            Name = "Marvel R"
                        },
                        new
                        {
                            Code = "mg_one",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/one.webp",
                            IsActive = true,
                            Name = "One"
                        },
                        new
                        {
                            Code = "mg_rx5",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/rx5.webp",
                            IsActive = true,
                            Name = "RX5"
                        },
                        new
                        {
                            Code = "mg_zs",
                            BrandId = "mg",
                            ImgUrl = "/models/mg/zs.webp",
                            IsActive = true,
                            Name = "ZS"
                        },
                        new
                        {
                            Code = "mini_aceman",
                            BrandId = "mini",
                            ImgUrl = "/models/mini/aceman.webp",
                            IsActive = true,
                            Name = "Aceman"
                        },
                        new
                        {
                            Code = "mini_coopercabrio",
                            BrandId = "mini",
                            ImgUrl = "/models/mini/coopercabrio.webp",
                            IsActive = true,
                            Name = "Cooper Cabrio"
                        },
                        new
                        {
                            Code = "mini_countryman",
                            BrandId = "mini",
                            ImgUrl = "/models/mini/countryman.webp",
                            IsActive = true,
                            Name = "Countryman"
                        },
                        new
                        {
                            Code = "mini_couperelectric",
                            BrandId = "mini",
                            ImgUrl = "/models/mini/couperelectric.webp",
                            IsActive = true,
                            Name = "Cooper Electric"
                        },
                        new
                        {
                            Code = "mitsubishi_asx",
                            BrandId = "mitsubishi",
                            ImgUrl = "/models/mitsubishi/asx.webp",
                            IsActive = true,
                            Name = "ASX"
                        },
                        new
                        {
                            Code = "mitsubishi_eclipsecross",
                            BrandId = "mitsubishi",
                            ImgUrl = "/models/mitsubishi/eclipsecross.webp",
                            IsActive = true,
                            Name = "Eclipse Cross"
                        },
                        new
                        {
                            Code = "mitsubishi_l200",
                            BrandId = "mitsubishi",
                            ImgUrl = "/models/mitsubishi/l200.webp",
                            IsActive = true,
                            Name = "L200"
                        },
                        new
                        {
                            Code = "mitsubishi_pajero",
                            BrandId = "mitsubishi",
                            ImgUrl = "/models/mitsubishi/pajero.webp",
                            IsActive = true,
                            Name = "Pajero"
                        },
                        new
                        {
                            Code = "mitsubishi_pajerosport",
                            BrandId = "mitsubishi",
                            ImgUrl = "/models/mitsubishi/pajerosport.webp",
                            IsActive = true,
                            Name = "Pajero Sport"
                        },
                        new
                        {
                            Code = "nissan_juke",
                            BrandId = "nissan",
                            ImgUrl = "/models/nissan/juke.webp",
                            IsActive = true,
                            Name = "Juke"
                        },
                        new
                        {
                            Code = "nissan_qashqai",
                            BrandId = "nissan",
                            ImgUrl = "/models/nissan/qashqai.webp",
                            IsActive = true,
                            Name = "Qashqai"
                        },
                        new
                        {
                            Code = "nissan_qashqaiepower",
                            BrandId = "nissan",
                            ImgUrl = "/models/nissan/qashqaiepower.webp",
                            IsActive = true,
                            Name = "Qashqai e-Power"
                        },
                        new
                        {
                            Code = "opel_astra",
                            BrandId = "opel",
                            ImgUrl = "/models/opel/astra.webp",
                            IsActive = true,
                            Name = "Astra"
                        },
                        new
                        {
                            Code = "opel_combocargo",
                            BrandId = "opel",
                            ImgUrl = "/models/opel/combocargo.webp",
                            IsActive = true,
                            Name = "Combo Cargo"
                        },
                        new
                        {
                            Code = "opel_corsa",
                            BrandId = "opel",
                            ImgUrl = "/models/opel/corsa.webp",
                            IsActive = true,
                            Name = "Corsa"
                        },
                        new
                        {
                            Code = "opel_crossland",
                            BrandId = "opel",
                            ImgUrl = "/models/opel/crossland.webp",
                            IsActive = true,
                            Name = "Crossland"
                        },
                        new
                        {
                            Code = "opel_mokka",
                            BrandId = "opel",
                            ImgUrl = "/models/opel/mokka.webp",
                            IsActive = true,
                            Name = "Mokka"
                        },
                        new
                        {
                            Code = "peugeot_2008",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/2008.webp",
                            IsActive = true,
                            Name = "2008"
                        },
                        new
                        {
                            Code = "peugeot_208",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/208.webp",
                            IsActive = true,
                            Name = "208"
                        },
                        new
                        {
                            Code = "peugeot_308",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/308.webp",
                            IsActive = true,
                            Name = "308"
                        },
                        new
                        {
                            Code = "peugeot_408",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/408.webp",
                            IsActive = true,
                            Name = "408"
                        },
                        new
                        {
                            Code = "peugeot_408gt",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/408gt.webp",
                            IsActive = true,
                            Name = "408 GT"
                        },
                        new
                        {
                            Code = "peugeot_boxer",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/boxer.webp",
                            IsActive = true,
                            Name = "Boxer"
                        },
                        new
                        {
                            Code = "peugeot_boxerdouble",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/boxerdouble.webp",
                            IsActive = true,
                            Name = "Boxer Double"
                        },
                        new
                        {
                            Code = "peugeot_expert",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/expert.webp",
                            IsActive = true,
                            Name = "Expert"
                        },
                        new
                        {
                            Code = "peugeot_expertcombi",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/expertcombi.webp",
                            IsActive = true,
                            Name = "Expert Combi"
                        },
                        new
                        {
                            Code = "peugeot_landtrekdouble",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/landtrekdouble.webp",
                            IsActive = true,
                            Name = "Landtrek Double"
                        },
                        new
                        {
                            Code = "peugeot_landtreksimple",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/landtreksimple.webp",
                            IsActive = true,
                            Name = "Landtrek Simple"
                        },
                        new
                        {
                            Code = "peugeot_partner",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/partner.webp",
                            IsActive = true,
                            Name = "Partner"
                        },
                        new
                        {
                            Code = "peugeot_rifter",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/rifter.webp",
                            IsActive = true,
                            Name = "Rifter"
                        },
                        new
                        {
                            Code = "peugeot_traveller",
                            BrandId = "peugeot",
                            ImgUrl = "/models/peugeot/traveller.webp",
                            IsActive = true,
                            Name = "Traveller"
                        },
                        new
                        {
                            Code = "porsche_911",
                            BrandId = "porsche",
                            ImgUrl = "/models/porsche/911.webp",
                            IsActive = true,
                            Name = "911"
                        },
                        new
                        {
                            Code = "porsche_cayenne",
                            BrandId = "porsche",
                            ImgUrl = "/models/porsche/cayenne.webp",
                            IsActive = true,
                            Name = "Cayenne"
                        },
                        new
                        {
                            Code = "porsche_cayennecoupe",
                            BrandId = "porsche",
                            ImgUrl = "/models/porsche/cayennecoupe.webp",
                            IsActive = true,
                            Name = "Cayenne Coupé"
                        },
                        new
                        {
                            Code = "porsche_macanelectric",
                            BrandId = "porsche",
                            ImgUrl = "/models/porsche/macanelectric.webp",
                            IsActive = true,
                            Name = "Macan Electric"
                        },
                        new
                        {
                            Code = "porsche_taycan",
                            BrandId = "porsche",
                            ImgUrl = "/models/porsche/taycan.webp",
                            IsActive = true,
                            Name = "Taycan"
                        },
                        new
                        {
                            Code = "porsche_taycancrossturismo",
                            BrandId = "porsche",
                            ImgUrl = "/models/porsche/taycancrossturismo.webp",
                            IsActive = true,
                            Name = "Taycan Cross Turismo"
                        },
                        new
                        {
                            Code = "renault_austral",
                            BrandId = "renault",
                            ImgUrl = "/models/renault/austral.webp",
                            IsActive = true,
                            Name = "Austral"
                        },
                        new
                        {
                            Code = "renault_clio",
                            BrandId = "renault",
                            ImgUrl = "/models/renault/clio.webp",
                            IsActive = true,
                            Name = "Clio"
                        },
                        new
                        {
                            Code = "renault_expresscombi",
                            BrandId = "renault",
                            ImgUrl = "/models/renault/expresscombi.webp",
                            IsActive = true,
                            Name = "Express Combi"
                        },
                        new
                        {
                            Code = "renault_expressvan",
                            BrandId = "renault",
                            ImgUrl = "/models/renault/expressvan.webp",
                            IsActive = true,
                            Name = "Express Van"
                        },
                        new
                        {
                            Code = "renault_master",
                            BrandId = "renault",
                            ImgUrl = "/models/renault/master.webp",
                            IsActive = true,
                            Name = "Master"
                        },
                        new
                        {
                            Code = "renault_megane",
                            BrandId = "renault",
                            ImgUrl = "/models/renault/megane.webp",
                            IsActive = true,
                            Name = "Megane"
                        },
                        new
                        {
                            Code = "renault_meganesedan",
                            BrandId = "renault",
                            ImgUrl = "/models/renault/meganesedan.webp",
                            IsActive = true,
                            Name = "Megane Sedan"
                        },
                        new
                        {
                            Code = "seat_arona",
                            BrandId = "seat",
                            ImgUrl = "/models/seat/arona.webp",
                            IsActive = true,
                            Name = "Arona"
                        },
                        new
                        {
                            Code = "seat_ateca",
                            BrandId = "seat",
                            ImgUrl = "/models/seat/ateca.webp",
                            IsActive = true,
                            Name = "Ateca"
                        },
                        new
                        {
                            Code = "seat_ibiza",
                            BrandId = "seat",
                            ImgUrl = "/models/seat/ibiza.webp",
                            IsActive = true,
                            Name = "Ibiza"
                        },
                        new
                        {
                            Code = "seat_leon",
                            BrandId = "seat",
                            ImgUrl = "/models/seat/leon.webp",
                            IsActive = true,
                            Name = "Leon"
                        },
                        new
                        {
                            Code = "skoda_fabia",
                            BrandId = "skoda",
                            ImgUrl = "/models/skoda/fabia.webp",
                            IsActive = true,
                            Name = "Fabia"
                        },
                        new
                        {
                            Code = "skoda_kamiq",
                            BrandId = "skoda",
                            ImgUrl = "/models/skoda/kamiq.webp",
                            IsActive = true,
                            Name = "Kamiq"
                        },
                        new
                        {
                            Code = "skoda_kushaq",
                            BrandId = "skoda",
                            ImgUrl = "/models/skoda/kushaq.webp",
                            IsActive = true,
                            Name = "Kushaq"
                        },
                        new
                        {
                            Code = "skoda_octavia",
                            BrandId = "skoda",
                            ImgUrl = "/models/skoda/octavia.webp",
                            IsActive = true,
                            Name = "Octavia"
                        },
                        new
                        {
                            Code = "skoda_scala",
                            BrandId = "skoda",
                            ImgUrl = "/models/skoda/scala.webp",
                            IsActive = true,
                            Name = "Scala"
                        },
                        new
                        {
                            Code = "kgm_korando",
                            BrandId = "kgm",
                            ImgUrl = "/models/kgm/korando.webp",
                            IsActive = true,
                            Name = "Korando"
                        },
                        new
                        {
                            Code = "kgm_musso",
                            BrandId = "kgm",
                            ImgUrl = "/models/kgm/musso.webp",
                            IsActive = true,
                            Name = "Musso"
                        },
                        new
                        {
                            Code = "kgm_rexton",
                            BrandId = "kgm",
                            ImgUrl = "/models/kgm/rexton.webp",
                            IsActive = true,
                            Name = "Rexton"
                        },
                        new
                        {
                            Code = "kgm_tivoli",
                            BrandId = "kgm",
                            ImgUrl = "/models/kgm/tivoli.webp",
                            IsActive = true,
                            Name = "Tivoli"
                        },
                        new
                        {
                            Code = "kgm_torres",
                            BrandId = "kgm",
                            ImgUrl = "/models/kgm/torres.webp",
                            IsActive = true,
                            Name = "Torres"
                        },
                        new
                        {
                            Code = "suzuki_baleno",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/baleno.webp",
                            IsActive = true,
                            Name = "Baleno"
                        },
                        new
                        {
                            Code = "suzuki_ciaz",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/ciaz.webp",
                            IsActive = true,
                            Name = "Ciaz"
                        },
                        new
                        {
                            Code = "suzuki_dzire",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/dzire.webp",
                            IsActive = true,
                            Name = "Dzire"
                        },
                        new
                        {
                            Code = "suzuki_ertiga",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/ertiga.webp",
                            IsActive = true,
                            Name = "Ertiga"
                        },
                        new
                        {
                            Code = "suzuki_fronx",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/fronx.webp",
                            IsActive = true,
                            Name = "Fronx"
                        },
                        new
                        {
                            Code = "suzuki_jimny3p",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/jimny3p.webp",
                            IsActive = true,
                            Name = "Jimny 3 Portes"
                        },
                        new
                        {
                            Code = "suzuki_jimny5p",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/jimny5p.webp",
                            IsActive = true,
                            Name = "Jimny 5 Portes"
                        },
                        new
                        {
                            Code = "suzuki_swift",
                            BrandId = "suzuki",
                            ImgUrl = "/models/suzuki/swift.webp",
                            IsActive = true,
                            Name = "Swift"
                        },
                        new
                        {
                            Code = "toyota_corollasedan",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/corollasedan.webp",
                            IsActive = true,
                            Name = "Corolla Sedan"
                        },
                        new
                        {
                            Code = "toyota_corollasedanhybride",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/corollasedanhybride.webp",
                            IsActive = true,
                            Name = "Corolla Sedan Hybride"
                        },
                        new
                        {
                            Code = "toyota_fortuner",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/fortuner.webp",
                            IsActive = true,
                            Name = "Fortuner"
                        },
                        new
                        {
                            Code = "toyota_hiacevan",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/hiacevan.webp",
                            IsActive = true,
                            Name = "Hiace Van"
                        },
                        new
                        {
                            Code = "toyota_hiluxdouble",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/hiluxdouble.webp",
                            IsActive = true,
                            Name = "Hilux Double Cabine"
                        },
                        new
                        {
                            Code = "toyota_hiluxsimple",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/hiluxsimple.webp",
                            IsActive = true,
                            Name = "Hilux Simple Cabine"
                        },
                        new
                        {
                            Code = "toyota_landcruiser300",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/landcruiser300.webp",
                            IsActive = true,
                            Name = "Land Cruiser 300"
                        },
                        new
                        {
                            Code = "toyota_landcruiser76",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/landcruiser76.webp",
                            IsActive = true,
                            Name = "Land Cruiser 76"
                        },
                        new
                        {
                            Code = "toyota_landcruiser79",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/landcruiser79.webp",
                            IsActive = true,
                            Name = "Land Cruiser 79"
                        },
                        new
                        {
                            Code = "toyota_prado",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/prado.webp",
                            IsActive = true,
                            Name = "Land Cruiser Prado"
                        },
                        new
                        {
                            Code = "toyota_rav4hybride",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/rav4hybride.webp",
                            IsActive = true,
                            Name = "RAV4 Hybride"
                        },
                        new
                        {
                            Code = "toyota_yariscrosshybride",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/yariscrosshybride.webp",
                            IsActive = true,
                            Name = "Yaris Cross Hybride"
                        },
                        new
                        {
                            Code = "toyota_yarishybride",
                            BrandId = "toyota",
                            ImgUrl = "/models/toyota/yarishybride.webp",
                            IsActive = true,
                            Name = "Yaris Hybride"
                        },
                        new
                        {
                            Code = "volkswagen_amarok",
                            BrandId = "volkswagen",
                            ImgUrl = "/models/volkswagen/amarok.webp",
                            IsActive = true,
                            Name = "Amarok"
                        },
                        new
                        {
                            Code = "volkswagen_caddycargo",
                            BrandId = "volkswagen",
                            ImgUrl = "/models/volkswagen/caddycargo.webp",
                            IsActive = true,
                            Name = "Caddy Cargo"
                        },
                        new
                        {
                            Code = "volkswagen_golf8",
                            BrandId = "volkswagen",
                            ImgUrl = "/models/volkswagen/golf8.webp",
                            IsActive = true,
                            Name = "Golf 8"
                        },
                        new
                        {
                            Code = "volkswagen_polo",
                            BrandId = "volkswagen",
                            ImgUrl = "/models/volkswagen/polo.webp",
                            IsActive = true,
                            Name = "Polo"
                        },
                        new
                        {
                            Code = "volkswagen_tcross",
                            BrandId = "volkswagen",
                            ImgUrl = "/models/volkswagen/tcross.webp",
                            IsActive = true,
                            Name = "T-Cross"
                        },
                        new
                        {
                            Code = "volkswagen_tiguan",
                            BrandId = "volkswagen",
                            ImgUrl = "/models/volkswagen/tiguan.webp",
                            IsActive = true,
                            Name = "Tiguan"
                        },
                        new
                        {
                            Code = "volkswagen_virtus",
                            BrandId = "volkswagen",
                            ImgUrl = "/models/volkswagen/virtus.webp",
                            IsActive = true,
                            Name = "Virtus"
                        },
                        new
                        {
                            Code = "volvo_ec40",
                            BrandId = "volvo",
                            ImgUrl = "/models/volvo/ec40.webp",
                            IsActive = true,
                            Name = "EC40"
                        },
                        new
                        {
                            Code = "volvo_ex30",
                            BrandId = "volvo",
                            ImgUrl = "/models/volvo/ex30.webp",
                            IsActive = true,
                            Name = "EX30"
                        },
                        new
                        {
                            Code = "volvo_xc40",
                            BrandId = "volvo",
                            ImgUrl = "/models/volvo/xc40.webp",
                            IsActive = true,
                            Name = "XC40"
                        },
                        new
                        {
                            Code = "volvo_xc60",
                            BrandId = "volvo",
                            ImgUrl = "/models/volvo/xc60.webp",
                            IsActive = true,
                            Name = "XC60"
                        },
                        new
                        {
                            Code = "volvo_xc90",
                            BrandId = "volvo",
                            ImgUrl = "/models/volvo/xc90.webp",
                            IsActive = true,
                            Name = "XC90"
                        },
                        new
                        {
                            Code = "wallys_annibal",
                            BrandId = "wallys",
                            ImgUrl = "/models/wallys/annibal.webp",
                            IsActive = true,
                            Name = "Annibal"
                        },
                        new
                        {
                            Code = "wallys_annibalxxl",
                            BrandId = "wallys",
                            ImgUrl = "/models/wallys/annibalxxl.webp",
                            IsActive = true,
                            Name = "Annibal XXL"
                        },
                        new
                        {
                            Code = "wallys_wolf",
                            BrandId = "wallys",
                            ImgUrl = "/models/wallys/wolf.webp",
                            IsActive = true,
                            Name = "Wolf"
                        });
                });

            modelBuilder.Entity("ConfiguratorAPI.Models.Trim", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .HasColumnType("text");

                    b.Property<int>("CylinderCount")
                        .HasColumnType("integer");

                    b.Property<int>("EnginePowerKW")
                        .HasColumnType("integer");

                    b.Property<string>("ExtendedCharacteristicsUrl")
                        .HasColumnType("text");

                    b.Property<int>("FiscalPower")
                        .HasColumnType("integer");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<decimal>("FullInsurance0PercentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FullInsurance4PercentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GeolocalisationPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("HorsePower")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaintenancePackagePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxSpeedKph")
                        .HasColumnType("integer");

                    b.Property<decimal>("PurchaseOptionPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer");

                    b.HasKey("Name", "ModelId");

                    b.HasIndex("ModelId");

                    b.ToTable("Trims");
                });

            modelBuilder.Entity("ConfiguratorAPI.Models.Model", b =>
                {
                    b.HasOne("ConfiguratorAPI.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("ConfiguratorAPI.Models.Trim", b =>
                {
                    b.HasOne("ConfiguratorAPI.Models.Model", "Model")
                        .WithMany("Trims")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("ConfiguratorAPI.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("ConfiguratorAPI.Models.Model", b =>
                {
                    b.Navigation("Trims");
                });
#pragma warning restore 612, 618
        }
    }
}
